"""followers

Revision ID: 67549b44dc8c
Revises: c0a9c521cc70
Create Date: 2025-06-29 10:36:32.410579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67549b44dc8c'
down_revision = 'c0a9c521cc70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
